server.port=8080

#=========== main variable ===========
db.username=
db.password=
db.url=
jwt.secret=
jwt.expiration.access=3600000
jwt.expiration.refresh=86400000
#========== config variable ==========
spring.r2dbc.url=${db.url}
spring.r2dbc.username=${db.username}
spring.r2dbc.password=${db.password}
spring.sql.init.mode=never

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
