server.port=8080

#=========== main variable ===========
db.username=
db.password=
db.url=
jwt.secret=
jwt.expiration.access=3600000
jwt.expiration.refresh=86400000
#========== config variable ==========
# R2DBC (основное реактивное подключение)
spring.r2dbc.url=r2dbc:postgresql://${db.url}
spring.r2dbc.username=${db.username}
spring.r2dbc.password=${db.password}

# JDBC (для Flyway)
spring.datasource.url=jdbc:postgresql://${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration

# Отключить schema.sql
spring.sql.init.mode=never

# Health endpoint для docker healthcheck: GET /api/health
