create table if not exists trouble(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text,
    description text,

    task_ids integer[]
);

/*create table if not exists implementer(
    id int GENERATED BY DEFAULT AS IDENTITY,

);*/

create table if not exists task(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text,
    description text,
    execute_date date,

    trouble_id int,
    implementer_id int
);