create table if not exists implementer(
    id int GENERATED BY DEFAULT AS IDENTITY,
    email text,
    password text,
    firstname text,
    middle_name text,
    lastname text,
    office_position text,

    task_ids integer[],
    role_ids integer[]
);

create table if not exists task(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text,
    description text,
    execute_date date,

    trouble_id int,
    implementer_id int
);

create table if not exists trouble(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text,
    description text,

    task_ids integer[]
);

create table if not exists role(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text,
    description text,

    authorities text[],
    implementers_ids int[]
);