package net.security.infosec.models;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

/*
create table if not exists division(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    division_head bigint,
    department_id bigint,
    title text,
    description text
);
 */

@Data
@NoArgsConstructor
public class Division {
    @Id
    private long id;
    private long departmentId;
    @NotBlank(message = "Не может быть пустым")
    private String title;
    @NotBlank(message = "Не может быть пустым")
    private String description;
    private int number;
}
