package net.security.infosec.models;

/*
create table if not exists employee(
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    name text,
    middle_name text,
    lastname text,

    position text,
    service text,

    cabinet int,
    address text,

    phone int
);
 */

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

@Data
@NoArgsConstructor
public class Employee {
    @Id
    private long id;

    private String name;
    private String middleName;
    private String lastname;

    private String position;
    private long serviceId;

    private int cabinet;
    private String address;

    private int phone;
}
