create table if not exists implementer(
    id int GENERATED BY DEFAULT AS IDENTITY,
    email text,
    password text,
    firstname text,
    middle_name text,
    lastname text,
    office_position text,
    role text,
    departmentRole text,

    task_ids integer[]
);

create table if not exists task(
    id int GENERATED BY DEFAULT AS IDENTITY,
    title text,
    description text,
    execute_date date,

    trouble_id int,
    implementer_id int
);

create table if not exists category(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text,
    description text,
    department_role text,

    trouble_ids integer[]
);

create table if not exists trouble(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name text,
    description text,
    department_role text,

    category_id int
);

create table if not exists department(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    number int,
    division_ids bigint[],
    title text,
    description text
);

create table if not exists division(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    number int,
    department_id bigint,
    title text,
    description text
);

create table if not exists employee(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    number int,
    name text,
    middle_name text,
    lastname text,
    position text,
    department_id bigint,
    division_id bigint,
    cabinet text,
    address text,
    phone text,
    personal_phone text,
    email text
);